name: 'Setup Atlas'
description: 'Installs a specific version of Atlas'
branding:
  icon: database
  color: 'blue'
author: 'Ariga'
inputs:
  version:
    description: 'Which version of Atlas to install, in the format of "v0.14.1"'
    required: false
    default: 'latest'
  cloud-token:
    description: API token to authenticate to an Atlas Cloud organization
    required: false
runs:
  using: "composite"
  steps:
    - if: runner.os != 'Windows'
      shell: bash
      run: curl -sSf https://atlasgo.sh | ATLAS_VERSION=${{inputs.version}} CI=true sh
    - if: runner.os == 'Windows'
      shell: pwsh
      run: |
        New-Item -Path "C:\Users\$env:USERNAME\bin" -ItemType Directory -Force
        curl -L https://release.ariga.io/atlas/atlas-windows-amd64-latest.exe -o "C:\Users\$env:USERNAME\AppData\Local\Microsoft\WindowsApps\atlas.exe"
    - name: Login to Atlas
      if: inputs.cloud-token != null
      shell: bash
      run: atlas login --token ${{ inputs.cloud-token }}
