name: Setup Atlas
run-name: I'm using Atlas 🚀
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  use-atlas:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
      - run: atlas version
